// Package accrual provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package accrual

// Defines values for AccrualOrderResponseStatus.
const (
	INVALID    AccrualOrderResponseStatus = "INVALID"
	PROCESSED  AccrualOrderResponseStatus = "PROCESSED"
	PROCESSING AccrualOrderResponseStatus = "PROCESSING"
	REGISTERED AccrualOrderResponseStatus = "REGISTERED"
)

// AccrualOrderResponse defines model for AccrualOrderResponse.
type AccrualOrderResponse struct {
	Accrual *float32                    `json:"accrual,omitempty"`
	Order   *string                     `json:"order,omitempty"`
	Status  *AccrualOrderResponseStatus `json:"status,omitempty"`
}

// AccrualOrderResponseStatus defines model for AccrualOrderResponse.Status.
type AccrualOrderResponseStatus string
