// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for OrderStatus.
const (
	INVALID    OrderStatus = "INVALID"
	PROCESSED  OrderStatus = "PROCESSED"
	PROCESSING OrderStatus = "PROCESSING"
	REGISTERED OrderStatus = "REGISTERED"
)

// Balance defines model for Balance.
type Balance struct {
	Current   *float32 `json:"current,omitempty"`
	Withdrawn *float32 `json:"withdrawn,omitempty"`
}

// Order defines model for Order.
type Order struct {
	Accrual    *float32     `json:"accrual,omitempty"`
	Number     *string      `json:"number,omitempty"`
	Status     *OrderStatus `json:"status,omitempty"`
	UploadedAt *time.Time   `json:"uploaded_at,omitempty"`
}

// OrderStatus defines model for Order.Status.
type OrderStatus string

// UserLogin defines model for UserLogin.
type UserLogin struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// UserRegistration defines model for UserRegistration.
type UserRegistration struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// Withdrawal defines model for Withdrawal.
type Withdrawal struct {
	Order       *string    `json:"order,omitempty"`
	ProcessedAt *time.Time `json:"processed_at,omitempty"`
	Sum         *float32   `json:"sum,omitempty"`
}

// WithdrawalRequest defines model for WithdrawalRequest.
type WithdrawalRequest struct {
	Order string  `json:"order"`
	Sum   float32 `json:"sum"`
}

// PostApiUserOrdersTextBody defines parameters for PostApiUserOrders.
type PostApiUserOrdersTextBody = string

// PostApiUserBalanceWithdrawJSONRequestBody defines body for PostApiUserBalanceWithdraw for application/json ContentType.
type PostApiUserBalanceWithdrawJSONRequestBody = WithdrawalRequest

// PostApiUserLoginJSONRequestBody defines body for PostApiUserLogin for application/json ContentType.
type PostApiUserLoginJSONRequestBody = UserLogin

// PostApiUserOrdersTextRequestBody defines body for PostApiUserOrders for text/plain ContentType.
type PostApiUserOrdersTextRequestBody = PostApiUserOrdersTextBody

// PostApiUserRegisterJSONRequestBody defines body for PostApiUserRegister for application/json ContentType.
type PostApiUserRegisterJSONRequestBody = UserRegistration
