-- migrations/000002_create_withdrawals_table.up.sql
BEGIN;

CREATE TABLE withdrawals (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    withdraw REAL,
    order_number VARCHAR(255),
    uploaded_at TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

COMMIT;