-- migrations/000001_create_users_table.up.sql
BEGIN;

CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(255) NOT NULL,
    hash BYTEA NOT NULL
);

CREATE UNIQUE INDEX idx_login ON users(login);

COMMIT;