-- migrations/000002_create_order_table.up.sql
BEGIN;

CREATE TABLE orders (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    order_number  VARCHAR(255) NOT NULL,
    status VARCHAR(255),
    accrual REAL,
    uploaded_at TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

COMMIT;